version: "3"
services:
  app:
    build: docker/
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  postgres:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lahortadb
    ports:
      - "3001:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@lahorta.com.br"
      PGADMIN_DEFAULT_PASSWORD: "devLahorta"
    ports:
      - "3002:80"
    depends_on:
      - postgres
